package com.teqbridgeltd.lucapp.notifications.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DictionaryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDictionaryAllPropertiesEquals(Dictionary expected, Dictionary actual) {
        assertDictionaryAutoGeneratedPropertiesEquals(expected, actual);
        assertDictionaryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDictionaryAllUpdatablePropertiesEquals(Dictionary expected, Dictionary actual) {
        assertDictionaryUpdatableFieldsEquals(expected, actual);
        assertDictionaryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDictionaryAutoGeneratedPropertiesEquals(Dictionary expected, Dictionary actual) {
        assertThat(actual)
            .as("Verify Dictionary auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDictionaryUpdatableFieldsEquals(Dictionary expected, Dictionary actual) {
        assertThat(actual)
            .as("Verify Dictionary relevant properties")
            .satisfies(a -> assertThat(a.getKeyName()).as("check keyName").isEqualTo(expected.getKeyName()))
            .satisfies(a -> assertThat(a.getKeyCode()).as("check keyCode").isEqualTo(expected.getKeyCode()))
            .satisfies(a -> assertThat(a.getLabel()).as("check label").isEqualTo(expected.getLabel()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDictionaryUpdatableRelationshipsEquals(Dictionary expected, Dictionary actual) {
        // empty method
    }
}
