package com.teqbridgeltd.lucapp.notifications.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class NotificationAttachmentAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNotificationAttachmentAllPropertiesEquals(NotificationAttachment expected, NotificationAttachment actual) {
        assertNotificationAttachmentAutoGeneratedPropertiesEquals(expected, actual);
        assertNotificationAttachmentAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNotificationAttachmentAllUpdatablePropertiesEquals(
        NotificationAttachment expected,
        NotificationAttachment actual
    ) {
        assertNotificationAttachmentUpdatableFieldsEquals(expected, actual);
        assertNotificationAttachmentUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNotificationAttachmentAutoGeneratedPropertiesEquals(
        NotificationAttachment expected,
        NotificationAttachment actual
    ) {
        assertThat(actual)
            .as("Verify NotificationAttachment auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNotificationAttachmentUpdatableFieldsEquals(NotificationAttachment expected, NotificationAttachment actual) {
        assertThat(actual)
            .as("Verify NotificationAttachment relevant properties")
            .satisfies(a -> assertThat(a.getFileName()).as("check fileName").isEqualTo(expected.getFileName()))
            .satisfies(a -> assertThat(a.getFileType()).as("check fileType").isEqualTo(expected.getFileType()))
            .satisfies(a -> assertThat(a.getFileSize()).as("check fileSize").isEqualTo(expected.getFileSize()))
            .satisfies(a -> assertThat(a.getFilePath()).as("check filePath").isEqualTo(expected.getFilePath()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNotificationAttachmentUpdatableRelationshipsEquals(
        NotificationAttachment expected,
        NotificationAttachment actual
    ) {
        assertThat(actual)
            .as("Verify NotificationAttachment relationships")
            .satisfies(a -> assertThat(a.getNotification()).as("check notification").isEqualTo(expected.getNotification()));
    }
}
